### ISSUE TITLE
Hi there,  you can controll this with a remote

### ISSUE THREAD

**Issue by crazy-george** [adamgreen/CHiP#1]
Hi,  Great work, helped me loads with exploring my CHiP.   Whilst doing that, i had one of my other wowwee bots on the side,( robosapien RS Media )  andby chance, the two pads on the controllers, are the same codes ( or close enough ) as CHiP and they make him walk forward and strife sideways. 

I will document the other codes i find over the next week, It was just a chance find.  

when i get time, i want to look at connections in the head.

**Comment by adamgreen** [comment]
Cool find!

> when i get time, i want to look at connections in the head.

Awesome! Let me know what you find!

**Comment by adamgreen** [comment]
If you document your discoveries online, I would love to link to it from this repository.

**Comment by adamgreen** [comment]
@crazy-george Please re-open and provide a link if you document your ChiP discoveries online.
