### ISSUE TITLE
Update on JTAG?

### ISSUE THREAD

**Issue by ThatHackerDudeFromCyberspace** [adamgreen/CHiP#3]
Since your first CHiP was bricked, did you try the JTAG on the second CHiP?

**Comment by ThatHackerDudeFromCyberspace** [comment]
Or have you tried re-flashing the firmware using the APP as your CHiP may be stuck in DFU mode (the bricked one)

**Comment by adamgreen** [comment]
> Since your first CHiP was bricked, did you try the JTAG on the second CHiP?

I haven't done anything on this project for a few years now.

> Or have you tried re-flashing the firmware using the APP as your CHiP may be stuck in DFU mode (the bricked one)

There is no code at all in the FLASH, not even the DFU firmware.

One thing that has happened to me since is while debugging another device, I had JLink offer to unbrick a device by bulk erasing it. It's possible that the version I was using at the time did this without me noticing when it detected the device had read protection enabled.

**Comment by ThatHackerDudeFromCyberspace** [comment]
Do you have any plans to JTAG the second chip or not?

**Comment by adamgreen** [comment]
Not for awhile. Are you thinking of trying?

**Comment by ThatHackerDudeFromCyberspace** [comment]
I would, but I don't have a JTAG and I kind of want to keep my CHiP unbricked

Probably stupid question: Couldn't you directly read the flash memory chip or is it embedded in the nrf?

**Comment by ThatHackerDudeFromCyberspace** [comment]
If I do, I will put my findings on a GitHub repo like you, maybe pull request

**Comment by ThatHackerDudeFromCyberspace** [comment]
> > Since your first CHiP was bricked, did you try the JTAG on the second CHiP?
> 
> I haven't done anything on this project for a few years now.
> 
> > Or have you tried re-flashing the firmware using the APP as your CHiP may be stuck in DFU mode (the bricked one)
> 
> There is no code at all in the FLASH, not even the DFU firmware.
> 
> One thing that has happened to me since is while debugging another device, I had JLink offer to unbrick a device by bulk erasing it. It's possible that the version I was using at the time did this without me noticing when it detected the device had read protection enabled.

It would appear that this was a thing that Segger JLinks did for "secured devices" back in 2018 at the latest

**Comment by adamgreen** [comment]
> I would, but I don't have a JTAG and I kind of want to keep my CHiP unbricked

That is the main reason I didn't just jump back in and try again with the SWD debugger right after I got the new board :)

> > Probably stupid question: Couldn't you directly read the flash memory chip or is it embedded in the nrf?

It is internal to the nRF microcontroller.

> If I do, I will put my findings on a GitHub repo like you, maybe pull request

Great!

> It would appear that this was a thing that Segger JLinks did for "secured devices" back in 2018 at the latest

Do you have a link? I would like to see if it matches what I saw happen at the time.

**Comment by ThatHackerDudeFromCyberspace** [comment]
Sure

https://forum.segger.com/index.php/Thread/5588-SOLVED-Automatic-mass-erase-on-Linux-upon-connecting-to-secured-device/?s=e0b8b50eef2b598a96b9bebe3f4c1738131e9d76

**Comment by adamgreen** [comment]
Ok. That definitely looks like what probably happened to me. I am surprised that I didn't find that forum post at the time I hit this as I went searching for something like this.

I wasn't going to try again until I had my own SWD code that I knew couldn't erase the FLASH. I had written the low level SWD protocol for the JTAGulator but didn't write enough high level code to read memory and read/write the CPU registers. I don't know if I will ever get back to this as I have lost the interest in hacking my CHiP these days.

**Comment by ThatHackerDudeFromCyberspace** [comment]
> JLink offer to unbrick a device by bulk erasing it. 

I actually just googled that
The main reason I'm trying to hack my CHiP is because wowwee decided to not release an update in 5 years and I grew bored of its features.

To be honest, this isn't the first time wowwee has released an updatable product and released little to no updates

**Comment by ThatHackerDudeFromCyberspace** [comment]
Actually I can't remember a product with more than 2 software updates

And none with feature updates

**Comment by adamgreen** [comment]
> The main reason I'm trying to hack my CHiP is because wowwee decided to not release an update in 5 years and I grew bored of its features.
> 
> To be honest, this isn't the first time wowwee has released an updatable product and released little to no updates

Yeah, I experienced the same with the MiP.

In some ways it makes sense. They are in the electronic toy business which is pretty fast paced and they need to concentrate their attention on producing the next hot holiday toy.

It would be cool if they would release a bit more information to help toy hackers once the sales of the toy have dropped off. I think the MiP release was a bit of an experiment in this area and maybe it didn't generate that much interest/sales so they abandoned it. The engineer who was the public face of the MiP SDK also left WowWee a year or so after the release so maybe that had an impact as well. He might have been the internal champion of such information releases.

They do have a BLE SDK for iOS and Arduino that you could use to write a new tablet/phone app yourself to control the CHiP.

What kind of hacks did you have in mind?

**Comment by ThatHackerDudeFromCyberspace** [comment]
Well since CHiP itself is… pretty dumb
I was planning on hooking up a pi zero and taking full control over it and using the pi as a processor rather than the nrf, but I didn’t want to just desolder it

I wanted to use the UART port instead of Bluetooth as using Bluetooth in such close range would be dumb (I did not know it was JTAG at the time)

I suppose I will have to reverse engineer your reverse engineered C library to work with Python
Although I could probably use cpython 


I could use the C library directly but I would like to make this more open to contributors

**Comment by ThatHackerDudeFromCyberspace** [comment]
>In some ways it makes sense. They are in the electronic toy business which is pretty fast paced and they need to concentrate their attention on producing the next hot holiday toy.

I prefer the simpler times, when an ex-nasa engineer was making walking talking linux robots (Robosapien RS Media)

**Comment by adamgreen** [comment]
> I wanted to use the UART port instead of Bluetooth as using Bluetooth in such close range would be dumb (I did not know it was JTAG at the time)

I never really found a UART port on the CHiP like exists on the MiP.

> I suppose I will have to reverse engineer your reverse engineered C library to work with Python Although I could probably use cpython

You don't really need to reverse engineer it as I documented the protocol [here](https://github.com/adamgreen/CHiP/blob/master/CHiP-BLE-Protocol.md)

>  I could use the C library directly but I would like to make this more open to contributors

I don't know that C is really the thing that causes a lack of contributors. I suspect that it is more lack of interest in CHiP hacking itself :)

**Comment by ThatHackerDudeFromCyberspace** [comment]
> I don't know that C is really the thing that causes a lack of contributors. I suspect that it is more lack of interest in CHiP hacking itself :)

probably, I just meant how I could write it in a simpler language to make it easier for beginners to contribute to it. Or to teach people simple coding using Python and a CHiP library. Then again, there is quite a lack of interest in CHiP hacking

Oh, I forgot about the documentation, thanks
